create table TNUMMAT_MatriUser (
	uuid_ VARCHAR(75) null,
	id_ LONG not null primary key,
	userId LONG,
	companyId LONG,
	education VARCHAR(75) null,
	countryid LONG,
	countryName VARCHAR(75) null,
	stateid LONG,
	stateName VARCHAR(75) null,
	districtid LONG,
	districtName VARCHAR(75) null,
	area VARCHAR(75) null,
	jamath VARCHAR(75) null,
	maritalStatus VARCHAR(75) null,
	height DOUBLE,
	weight DOUBLE,
	ConvertMuslim VARCHAR(75) null,
	primaryId VARCHAR(75) null,
	imageId LONG,
	createDate DATE null,
	modifiedDate DATE null,
	color VARCHAR(75) null,
	bio VARCHAR(75) null,
	malechild VARCHAR(75) null,
	femalechild VARCHAR(75) null,
	MothertongueLanguage VARCHAR(75) null,
	LivingPlace VARCHAR(75) null,
	Monthlyincome DOUBLE
);