/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package ummat_startup_details.model.impl;

import ummat_startup_details.model.MatriUser;

import ummat_startup_details.service.MatriUserLocalServiceUtil;

/**
 * The extended model base implementation for the MatriUser service. Represents a row in the &quot;TNUMMAT_MatriUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MatriUserImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MatriUserImpl
 * @see MatriUser
 * @generated
 */
public abstract class MatriUserBaseImpl
	extends MatriUserModelImpl implements MatriUser {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a matri user model instance should use the <code>MatriUser</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			MatriUserLocalServiceUtil.addMatriUser(this);
		}
		else {
			MatriUserLocalServiceUtil.updateMatriUser(this);
		}
	}

}