/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package ummat_startup_details.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the MatriUser service. Represents a row in the &quot;TNUMMAT_MatriUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>ummat_startup_details.model.impl.MatriUserModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>ummat_startup_details.model.impl.MatriUserImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MatriUser
 * @generated
 */
@ProviderType
public interface MatriUserModel
	extends BaseModel<MatriUser>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a matri user model instance should use the {@link MatriUser} interface instead.
	 */

	/**
	 * Returns the primary key of this matri user.
	 *
	 * @return the primary key of this matri user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this matri user.
	 *
	 * @param primaryKey the primary key of this matri user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this matri user.
	 *
	 * @return the uuid of this matri user
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this matri user.
	 *
	 * @param uuid the uuid of this matri user
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this matri user.
	 *
	 * @return the ID of this matri user
	 */
	public long getId();

	/**
	 * Sets the ID of this matri user.
	 *
	 * @param id the ID of this matri user
	 */
	public void setId(long id);

	/**
	 * Returns the user ID of this matri user.
	 *
	 * @return the user ID of this matri user
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this matri user.
	 *
	 * @param userId the user ID of this matri user
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this matri user.
	 *
	 * @return the user uuid of this matri user
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this matri user.
	 *
	 * @param userUuid the user uuid of this matri user
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the company ID of this matri user.
	 *
	 * @return the company ID of this matri user
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this matri user.
	 *
	 * @param companyId the company ID of this matri user
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the education of this matri user.
	 *
	 * @return the education of this matri user
	 */
	@AutoEscape
	public String getEducation();

	/**
	 * Sets the education of this matri user.
	 *
	 * @param education the education of this matri user
	 */
	public void setEducation(String education);

	/**
	 * Returns the countryid of this matri user.
	 *
	 * @return the countryid of this matri user
	 */
	public long getCountryid();

	/**
	 * Sets the countryid of this matri user.
	 *
	 * @param countryid the countryid of this matri user
	 */
	public void setCountryid(long countryid);

	/**
	 * Returns the country name of this matri user.
	 *
	 * @return the country name of this matri user
	 */
	@AutoEscape
	public String getCountryName();

	/**
	 * Sets the country name of this matri user.
	 *
	 * @param countryName the country name of this matri user
	 */
	public void setCountryName(String countryName);

	/**
	 * Returns the stateid of this matri user.
	 *
	 * @return the stateid of this matri user
	 */
	public long getStateid();

	/**
	 * Sets the stateid of this matri user.
	 *
	 * @param stateid the stateid of this matri user
	 */
	public void setStateid(long stateid);

	/**
	 * Returns the state name of this matri user.
	 *
	 * @return the state name of this matri user
	 */
	@AutoEscape
	public String getStateName();

	/**
	 * Sets the state name of this matri user.
	 *
	 * @param stateName the state name of this matri user
	 */
	public void setStateName(String stateName);

	/**
	 * Returns the districtid of this matri user.
	 *
	 * @return the districtid of this matri user
	 */
	public long getDistrictid();

	/**
	 * Sets the districtid of this matri user.
	 *
	 * @param districtid the districtid of this matri user
	 */
	public void setDistrictid(long districtid);

	/**
	 * Returns the district name of this matri user.
	 *
	 * @return the district name of this matri user
	 */
	@AutoEscape
	public String getDistrictName();

	/**
	 * Sets the district name of this matri user.
	 *
	 * @param districtName the district name of this matri user
	 */
	public void setDistrictName(String districtName);

	/**
	 * Returns the area of this matri user.
	 *
	 * @return the area of this matri user
	 */
	@AutoEscape
	public String getArea();

	/**
	 * Sets the area of this matri user.
	 *
	 * @param area the area of this matri user
	 */
	public void setArea(String area);

	/**
	 * Returns the jamath of this matri user.
	 *
	 * @return the jamath of this matri user
	 */
	@AutoEscape
	public String getJamath();

	/**
	 * Sets the jamath of this matri user.
	 *
	 * @param jamath the jamath of this matri user
	 */
	public void setJamath(String jamath);

	/**
	 * Returns the marital status of this matri user.
	 *
	 * @return the marital status of this matri user
	 */
	@AutoEscape
	public String getMaritalStatus();

	/**
	 * Sets the marital status of this matri user.
	 *
	 * @param maritalStatus the marital status of this matri user
	 */
	public void setMaritalStatus(String maritalStatus);

	/**
	 * Returns the height of this matri user.
	 *
	 * @return the height of this matri user
	 */
	public Double getHeight();

	/**
	 * Sets the height of this matri user.
	 *
	 * @param height the height of this matri user
	 */
	public void setHeight(Double height);

	/**
	 * Returns the weight of this matri user.
	 *
	 * @return the weight of this matri user
	 */
	public double getWeight();

	/**
	 * Sets the weight of this matri user.
	 *
	 * @param weight the weight of this matri user
	 */
	public void setWeight(double weight);

	/**
	 * Returns the convert muslim of this matri user.
	 *
	 * @return the convert muslim of this matri user
	 */
	@AutoEscape
	public String getConvertMuslim();

	/**
	 * Sets the convert muslim of this matri user.
	 *
	 * @param ConvertMuslim the convert muslim of this matri user
	 */
	public void setConvertMuslim(String ConvertMuslim);

	/**
	 * Returns the primary ID of this matri user.
	 *
	 * @return the primary ID of this matri user
	 */
	@AutoEscape
	public String getPrimaryId();

	/**
	 * Sets the primary ID of this matri user.
	 *
	 * @param primaryId the primary ID of this matri user
	 */
	public void setPrimaryId(String primaryId);

	/**
	 * Returns the image ID of this matri user.
	 *
	 * @return the image ID of this matri user
	 */
	public long getImageId();

	/**
	 * Sets the image ID of this matri user.
	 *
	 * @param imageId the image ID of this matri user
	 */
	public void setImageId(long imageId);

	/**
	 * Returns the create date of this matri user.
	 *
	 * @return the create date of this matri user
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this matri user.
	 *
	 * @param createDate the create date of this matri user
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this matri user.
	 *
	 * @return the modified date of this matri user
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this matri user.
	 *
	 * @param modifiedDate the modified date of this matri user
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the color of this matri user.
	 *
	 * @return the color of this matri user
	 */
	@AutoEscape
	public String getColor();

	/**
	 * Sets the color of this matri user.
	 *
	 * @param color the color of this matri user
	 */
	public void setColor(String color);

	/**
	 * Returns the bio of this matri user.
	 *
	 * @return the bio of this matri user
	 */
	@AutoEscape
	public String getBio();

	/**
	 * Sets the bio of this matri user.
	 *
	 * @param bio the bio of this matri user
	 */
	public void setBio(String bio);

	/**
	 * Returns the malechild of this matri user.
	 *
	 * @return the malechild of this matri user
	 */
	@AutoEscape
	public String getMalechild();

	/**
	 * Sets the malechild of this matri user.
	 *
	 * @param malechild the malechild of this matri user
	 */
	public void setMalechild(String malechild);

	/**
	 * Returns the femalechild of this matri user.
	 *
	 * @return the femalechild of this matri user
	 */
	@AutoEscape
	public String getFemalechild();

	/**
	 * Sets the femalechild of this matri user.
	 *
	 * @param femalechild the femalechild of this matri user
	 */
	public void setFemalechild(String femalechild);

	/**
	 * Returns the mothertongue language of this matri user.
	 *
	 * @return the mothertongue language of this matri user
	 */
	@AutoEscape
	public String getMothertongueLanguage();

	/**
	 * Sets the mothertongue language of this matri user.
	 *
	 * @param MothertongueLanguage the mothertongue language of this matri user
	 */
	public void setMothertongueLanguage(String MothertongueLanguage);

	/**
	 * Returns the living place of this matri user.
	 *
	 * @return the living place of this matri user
	 */
	@AutoEscape
	public String getLivingPlace();

	/**
	 * Sets the living place of this matri user.
	 *
	 * @param LivingPlace the living place of this matri user
	 */
	public void setLivingPlace(String LivingPlace);

	/**
	 * Returns the monthlyincome of this matri user.
	 *
	 * @return the monthlyincome of this matri user
	 */
	public double getMonthlyincome();

	/**
	 * Sets the monthlyincome of this matri user.
	 *
	 * @param Monthlyincome the monthlyincome of this matri user
	 */
	public void setMonthlyincome(double Monthlyincome);

	@Override
	public MatriUser cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}