/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ummat.slayer.model.impl;

import com.ummat.slayer.model.District;
import com.ummat.slayer.service.DistrictLocalServiceUtil;

/**
 * The extended model base implementation for the District service. Represents a row in the &quot;District&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DistrictImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DistrictImpl
 * @see District
 * @generated
 */
public abstract class DistrictBaseImpl
	extends DistrictModelImpl implements District {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a district model instance should use the <code>District</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			DistrictLocalServiceUtil.addDistrict(this);
		}
		else {
			DistrictLocalServiceUtil.updateDistrict(this);
		}
	}

}