/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ummat.slayer.model.impl;

import com.ummat.slayer.model.Locality;
import com.ummat.slayer.service.LocalityLocalServiceUtil;

/**
 * The extended model base implementation for the Locality service. Represents a row in the &quot;Locality&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LocalityImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LocalityImpl
 * @see Locality
 * @generated
 */
public abstract class LocalityBaseImpl
	extends LocalityModelImpl implements Locality {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a locality model instance should use the <code>Locality</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			LocalityLocalServiceUtil.addLocality(this);
		}
		else {
			LocalityLocalServiceUtil.updateLocality(this);
		}
	}

}